### ISSUE TITLE
Integrate TravisCI For Your Repo To Run Unit Test In Every Commit

### ISSUE THREAD

**Issue by umutphp** [ebru/sending-messages#1]
If you integrate TravisCI with your project, you can trigger unit tests after every commit. The results are displayed on commit interface of Github. Additionally, you can use badges in your Readme file to show the last status of your repo.

**Comment by ebru** [comment]
Integrated! Build status badge is added to readme as well.

**Comment by umutphp** [comment]
Cool :)
